### ISSUE TITLE
Danger! Deletes other files without warning.

### ISSUE THREAD

**Issue by TannerTechnical** [hbowie/notenik-project#1]
I was testing Notenik (v1.40) for the first time and went to save the introductory file to my desktop. Notenik happily deleted **ALL** the files on my desktop without any warning whatsoever. To top it off no file (or directory) was created by Notenik.

I've uninstalled Notenik until this has been fully addressed. Applications should **NEVER** delete a user's files without their clear and explicit approval via warning dialog(s).

**Comment by hbowie** [comment]
Thanks for letting me know! I’ll investigate and see what might be going on.

**Comment by hbowie** [comment]
First of all, thanks for letting me know! And I apologize for the problem. Hoping that you were able to restore everything to your desktop from a backup of some sort. 

Second of all, I've corrected the problem in the code on GitHub, and currently have a version 1.4.1 in the queue for release to the App Store which will fix the problem. 

Third, brilliant idea to try to save the help notes to your desktop! It had never occurred to me before that someone might try to do that, but it really does make a lot of sense. 

Fourth, here are the details of what was going on and how it's been fixed. 

In general, Notenik expects you to create a new folder to hold a new collection of notes, and then select that folder. It's a little awkward, but I don't know of a more straightforward way to allow the user to basically put as many collections of notes wherever they want. 

So when you opened the help notes, and then did a save as to your desktop, Notenik assumed you wanted the selected folder (your desktop folder) to become, in its entirety, a Notenik Collection. 

When doing a Save As, Notenik uses a native Mac API to copy the entire current collection over to the new location. Unfortunately, in order to use this API, the target folder must not yet exist. So in order to make this work, Notenik deletes the target folder (assuming it's an empty folder that you've just created) and then does the copy. 

I'm a little surprised that macOS allowed Notenik to delete a privileged folder such as your Desktop folder. Apparently, though, it jumped to your defense (although a little too late) preventing Notenik from copying something else to that location. 

I've updated the documentation to make it a little clearer how Notenik works in a case like this. 

More importantly, of course, I've updated the code to prevent something like this from happening again. I've added a couple of checks to prevent this. First, I'm explicitly checking to make sure the target folder is not named 'Desktop' or 'Documents'. Second, I'm checking to make sure the target folder is empty. If either check fails, then Notenik will abort the Save As process before deleting or copying anything. 

Thanks again, and let me know if any further questions!
